CREATE TABLE records (
	id bigint generated by default as identity primary key,
	created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tank_add REAL not null,
  tank_mark SMALLINT not null,
  kilometrage INT not null
);